<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '注： 既存レコードを編集すると、{category}名とその設定が変更されます。',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '注：既存レコードを編集すると、{category}名は変更されます（設定は保持されます）。',
    'Abort any changes and reset settings' => '変更を中止し、設定をリセットします。',
    'Apply' => '適用',
    'Are you sure you want to delete the setting?' => '設定を削除してよいですか？',
    'Configure Order and Display of Grid Columns' => 'グリッド列の表示、順の設定',
    'Default Filter' => 'デフォルトフィルタ',
    'Default Sort' => 'デフォルトソート',
    'Delete' => '削除',
    'Filter Configuration' => 'フィルタ設定',
    'Filter Name' => 'フィルタ名',
    'Grid Theme' => 'グリッドテーマ',
    'Hidden / Fixed Columns' => '見せない/固定　列',
    'Integer between {min} to {max}' => '{mix}から{max}の間の整数',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '操作できません！dynagrid設定{params}に不適切なリクエストがありました。',
    'Page Size' => 'ページサイズ',
    'Personalize Grid Configuration' => 'パーソナライズグリッド設定',
    'Personalize grid settings' => 'パーソナライズグリッド設定',
    'Remove saved grid settings' => '保存済みグリッド設定を除く',
    'Reset' => 'リセット',
    'Save' => '保存',
    'Save / Edit Grid {title}' => '保存 / 編集　{title}グリッド',
    'Save / edit grid {category}' => '保存 / 編集　{category}',
    'Save grid settings' => 'グリッド設定の保存',
    'Saved Filters' => '保存されたフィルタ',
    'Saved Sorts' => '保存されたソート',
    'Saving and applying configuration' => '設定の保存と適用',
    'Select a filter...' => 'フィルタを選択...',
    'Select a sort...' => 'ソートを選択...',
    'Select a theme...' => 'テーマを選択...',
    'Select theme to style grid' => 'スタイルグリッドにテーマを選択...',
    'Select...' => '選択...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => '{category}グリッド状態の保存名を設定してください。もしくは、すでに保存した情報を使うこともできます。',
    'Set default grid filter criteria' => 'グリッドフィルタのデフォルト条件を設定',
    'Set default grid sort criteria' => 'グリッドソートのデフォルト条件を設定',
    'Sort Configuration' => 'ソート設定',
    'Sort Name' => 'ソート名',
    'Trash' => 'ゴミ箱',
    'Trashing all personalizations' => '個人設定を全てゴミ箱へ',
    'Visible Columns' => '見える列',
    'ascending' => '昇順',
    'descending' => '降順',
    'filter' => 'フィルタ',
    'grid' => 'グリッド',
    'rows per page' => 'ページあたり行',
    'sort' => 'ソート',
];
